fixtures:
  repositories:
    archive: "https://github.com/puppet-community/puppet-archive.git"
    java: "https://github.com/mmarseglia/puppetlabs-java.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    sonarqube: "#{source_dir}"
