fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo"
    maven: "https://github.com/maestrodev/puppet-maven.git"
  symlinks:
    sonarqube: "#{source_dir}"
