---
before_install:
  - rm -f Gemfile.lock

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.9"
  - "2.2.5"
  - "2.3.1"

env:
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.5.1" STRICT_VARIABLES=yes

matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    # Puppet < 3.5.0 is broken under ruby 2.1 https://tickets.puppetlabs.com/browse/PUP-1243
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 3.4.0"
    # NameError: uninitialized constant syck
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.2.3
      env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
